### PR TITLE
Fake Data Generator

### PR DESCRIPTION
**Pull request by joshwalawender**
Add quick and dirty generator of fake data for testing and development of cloud platform to ingest processed data from individual units and combine and store the light curves on the cloud.

@wtgee @kstoreyf

### CODE REVIEW

**Comment by joshwalawender** [comment]
I should also note that this code is just a starting point.  We can add more features as we go along.  For example, we could add the ability to inject fake signals in to the light curves such as variable stars, actual transits, or instrumental signals of some sort.  We will also flesh out the metadata as time goes on.

For now the generated FITS cubes are pure noise. We plan to process on the individual units, so the PSCs are only sent to the cloud for archiving, so I only wanted to simulate the size of the file and the metadata.  If we want to, we can add photometric signals to them later.

**Comment by wtgee** [comment]
@joshwalawender lines 40-41 aren't working for me. I'm not sure the `extend` works like you want it to. If you just assign directly to the header by replacing line 40 it works fine for me.

**Comment by joshwalawender** [comment]
@wtgee Weird, must be different astropy versions or something.  Whatever works is fine.  I didn't research which is the preferred API for adding header entries, there are several ways to do it within astropy.io.fits.

How shall we run this?  @kstoreyf do you want to run it locally to generate test data whenever you need it?  If so, you just have to coordinate with @wtgee on formats (i.e. JSON for the light curve).  We can eventually set it up to test uploading data from a unit to the cloud as well.

**Comment by kstoreyf** [comment]
@joshw @wtgee I edited a local copy to generate JSON test light curves and I'm running it locally. Sounds good about eventually testing to upload to the cloud

**Comment by joshwalawender** [comment]
@kstoreyf I've merged this, so you can either push your edits directly to this PANOPTES repo or do a pull request if you've forked it.

**Pull request merged**
